"""empty message

Revision ID: 389eebe0d809
Revises: a01917928bbb
Create Date: 2020-10-20 15:17:22.734234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389eebe0d809'
down_revision = 'a01917928bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios_nuevos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dzname', sa.String(), nullable=False),
    sa.Column('dzEmail', sa.String(), nullable=False),
    sa.Column('dzOther_phone', sa.Integer(), nullable=False),
    sa.Column('dzOther_sex', sa.String(), nullable=False),
    sa.Column('dzMessage', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_nuevos')
    # ### end Alembic commands ###
